In [1]:
import re
import pandas as pd

In [2]:
f = open('WhatsApp Chat with Section A unofficial.txt', 'r', encoding = 'utf-8')

In [3]:
data = f.read() # storing chats in data variable

In [4]:
print(data)

12/09/25, 16:04 - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*
12/09/25, 20:34 - Aditya AA EC GLA: Communication k assignment hogyaa kisika...?
12/09/25, 20:40 - Vinayak GLA 2nd Year: Yes
12/09/25, 20:53 - +91 788 725 2559: Bhej do
12/09/25, 20:53 - +91 84398 26596: Bhjo
12/09/25, 20:56 - +91 90768 32806: Bhejo
12/09/25, 20:59 - Aditya AA EC GLA: Aaj bhi quiz h kyaa...?
12/09/25, 20:59 - Shubh AA 2nd year GLA: Nhi
13/09/25, 09:56 - Damroo AA CE: Quiz chalu hone vali he 10bje se Vlsi ki
13/09/25, 10:07 - +91 76186 24348: Answer bhej do
13/09/25, 10:08 - Vinayak GLA 2nd Year:
13/09/25, 10:09 - Umang Goyal: Kitne hue sahi
13/09/25, 10:11 - Damroo AA CE: Ye lo pure 20 ke 20 sahi he
13/09/25, 10:19 - Sandeep Solanki: Hein
13/09/25, 10:19 - Sandeep Solanki: Tune save and next nhi kre ky
13/09/25, 10:19 - Umang Goyal: Are
13/09/25, 10:19 - Shubh AA 2nd year GLA: Saare save kiye the
13/09/25, 10:19 - Shubh AA 2nd year GLA: Hn
13/09/25, 10:19 - Sandeep Solanki: Upr se hi switch kre hain ky
13/09/25, 10:20 - Sandeep Solanki: Aare
13/09/25, 10:20 - Shubh AA 2nd year GLA: Nhi
13/09/25, 10:20 - Sandeep Solanki: Chud gye guru tum toh
13/09/25, 10:20 - Shubh AA 2nd year GLA: Pehli baar thodi de raha hu
13/09/25, 10:20 - Sandeep Solanki: Mdm ko inform krde
13/09/25, 10:20 - Sandeep Solanki: Abhi turant
13/09/25, 10:21 - Shubh AA 2nd year GLA: Hn
13/09/25, 10:22 - +91 97193 96608: Waw cr
13/09/25, 17:17 - Shubh AA 2nd year GLA: Bhai kisi ka verilog ka assignment ho gya ho toh bhej do
13/09/25, 17:18 - Vinayak GLA 2nd Year: Bhai baj do koi
13/09/25, 21:02 - Yogesh Agrawal: Quiz active ho gya h D.comm ka
13/09/25, 21:02 - Upanshu Nayak AA CE: Answer bhejdo
13/09/25, 21:03 - Yogesh Agrawal: Yes koi answers bhej do
13/09/25, 21:05 - Upanshu Nayak AA CE: Answer
13/09/25, 21:10 - +91 91701 56635: Bhai answer bhej do kui
13/09/25, 21:11 - +91 85338 44236:
13/09/25, 21:13 - +91 85338 44236: Bhai log usme 8 shi h
13/09/25, 21:13 - Yogesh Agrawal: Ha hme dikh rha h
13/09/25, 21:16 - Umang Goyal: 10 ka c bhi nhi hajn
13/09/25, 21:16 - Umang Goyal: Hain
13/09/25, 21:16 - +91 90272 00819: D hai 10 ka
13/09/25, 21:17 - Umang Goyal: 3 ka b bhi nhi hain
13/09/25, 21:35 - Vinayak GLA 2nd Year: Bhai verilog ka assignment baj do koi
13/09/25, 23:38 - +91 85338 44236: Hnn woh muje ptaa h....sbbko dikh rha h
...tere jeso ke liye hi likha tha.... chlo shi h phir tujhe dikh rha h toh
14/09/25, 01:58 - Damroo AA CE pinned a message
14/09/25, 01:59 - Damroo AA CE: Last date is 17th september
14/09/25, 02:00 - +91 84398 26596: H ky ye?
14/09/25, 02:00 - Damroo AA CE: Nptel project management for mangers week-8 Answers
14/09/25, 15:42 - +91 78190 09204: Bhai Verilog ka assignment bhej do koi
15/09/25, 12:15 - Sameeraj AA EC: https://www.instagram.com/reel/DOdyo7tCFIS/?igsh=OXd6Ymp1dnlibDE2
15/09/25, 12:17 - Aditya AA EC GLA: <Media omitted>
15/09/25, 15:47 - +91 788 725 2559: https://youtu.be/tDN3cdFUatM?si=rJjt6burAr3c1FhG
15/09/25, 20:08 - +91 90272 00819: https://youtube.com/shorts/MMf9Y2lMbDQ?si=Mb3SHTTZ1xjyMlnd
16/09/25, 00:22 - Sameeraj AA EC: https://www.instagram.com/reel/DOJK4fmjDv-/?igsh=aDlpaWp1dng4czE=
16/09/25, 12:12 - Damroo AA CE:
16/09/25, 12:14 - Aditya AA EC GLA: 4 glt hai isme
16/09/25, 12:14 - Shubh AA 2nd year GLA: Konse
16/09/25, 12:14 - Aditya AA EC GLA: Dundh le khud
16/09/25, 12:16 - Sameeraj AA EC: @⁨Shubh AA 2nd year GLA⁩
16/09/25, 12:16 - Sameeraj AA EC: Abhi submit kar karna
16/09/25, 12:16 - Shubh AA 2nd year GLA: Kya
16/09/25, 12:18 - Sandeep Solanki: Aare quiz hai quiz dede
17/09/25, 13:04 - Damroo AA CE: DBLnv3B9t3HdfpY493QNXQ==.pdf https://share.google/fyly9L49rwPJDOF3W
17/09/25, 14:17 - Aditya AA EC GLA: 2-3 class cancel hai...mam nhi aarhe... tbiyat khrab hone h vjh s to...awaz mt Krna k baki koi aur teacher aajye sab dekh k...
17/09/25, 14:18 - Shubh AA 2nd year GLA: Present laga diyo
17/09/25, 14:18 - Shubh AA 2nd year GLA: 30, 41 and 25 yaha se
17/09/25, 14:19 - Aditya AA EC GLA: Bhailog class cancel nhi hai...bss mam present nhi hai...halla mt kro k koi aur teacher aajye... unka name p bhi aajyege baat aur hamra bhi lanka lgege
17/09/25, 14:26 - +91 90768 32806: 13 ec cs pe bhi present laga diyo
17/09/25, 14:26 - +91 788 725 2559: 11 ec cs
17/09/25, 14:27 - +91 788 725 2559: Mere bhi laga dena
17/09/25, 14:27 - +91 89603 78812: 08 ec CS also present
17/09/25, 15:27 - Damroo AA CE: Channel Length Modulation (CLM) in MOSFET is kind of like what happens when you pinch a water pipe:

Normally, when a MOSFET is in saturation, the current (Id) is supposed to be constant and not depend on drain voltage (Vds).

But in reality, as Vds increases, the depletion region at the drain expands and eats into the channel.

This makes the effective channel length shorter (like making the pipe shorter).

Shorter channel → less resistance → current increases slightly with Vds.


👉 So, Channel Length Modulation means the drain current in saturation is not perfectly flat, but increases with drain voltage.

It’s modeled by adding a factor  to the current equation. <This message was edited>
17/09/25, 19:01 - Damroo AA CE: aaj last date he week-8 ki
17/09/25, 22:24 - +91 788 725 2559: https://youtu.be/Gq8M-dWL2pY?si=0CxQLDxYI2GlL4iD
18/09/25, 13:19 - PIYUSH SHARMA: This message was deleted
18/09/25, 13:20 - +91 63978 13356: Nhi Bhai😒
18/09/25, 13:20 - +91 97612 84100: This message was deleted
18/09/25, 13:21 - +91 63978 13356: This message was deleted
18/09/25, 13:28 - +91 97612 84100: This message was deleted
18/09/25, 15:40 - Aditya AA EC GLA removed Dev Mohan
18/09/25, 16:08 - +91 74179 61902: Bhaiyo kisi ko agr ek black color ki plastic ki bottle mile to btana
18/09/25, 16:43 - +91 92598 36859: Yele bhai
18/09/25, 16:43 - +91 74179 61902: 😂
18/09/25, 16:43 - +91 74179 61902: Kl de diyo bhai
18/09/25, 16:44 - +91 92598 36859: Okk bhai
18/09/25, 16:44 - +91 74179 61902: Hmm
18/09/25, 20:47 - +91 97193 96608: https://www.instagram.com/reel/DOF93SEgL8A/?igsh=MWgzdzZ5aWRnNzZncw==
18/09/25, 20:47 - +91 97193 96608: Aditya cr
18/09/25, 21:46 - Umang Goyal: Nhi yogesh par sahi  baitha hai
18/09/25, 22:24 - Damroo AA CE: Agar kisi ki 19th august me leave lagi ho batado verbal aptitude ki attendance bhejni he
18/09/25, 22:25 - Upanshu Nayak AA CE: all present bhejdo!
18/09/25, 22:25 - +91 92598 36859: Yess i support this statement
18/09/25, 23:07 - Krishna AA CE: It is not possible!!
18/09/25, 23:08 - Krishna AA CE: Please give your names if you have leave!
18/09/25, 23:08 - +91 92598 36859: Mujhe sachin ko or shivam chaudhary ko present rkhna baaki mujhe frk nhi pdta
18/09/25, 23:08 - +91 92598 36859: 34,39,38
18/09/25, 23:09 - Krishna AA CE: Leave toh nhi h?
18/09/25, 23:09 - +91 92598 36859: Nooo
18/09/25, 23:09 - +91 89235 30004: 💦
18/09/25, 23:09 - Sameeraj AA EC: Abe jisko absent karvani hai vo bol do baki sab present hai by default jisko dikkat hai apna khud dekh le
18/09/25, 23:10 - +91 89235 30004: 👉🏻👌🏻💦
18/09/25, 23:10 - Krishna AA CE: Bhai btado jiska bhi h!
18/09/25, 23:11 - +91 92598 36859: Yogesh ko absent krdo
18/09/25, 23:12 - Yogesh Agrawal: Kiyu
18/09/25, 23:13 - +91 92598 36859: Ese hi
18/09/25, 23:14 - Yogesh Agrawal: Ese hi tu fir kisi aur ka bhi name le skta h mera hi kyu liya
18/09/25, 23:15 - +91 92598 36859: Kyuki tu bhaiii h
18/09/25, 23:15 - +91 92598 36859: M cahata hu tu sb cheej m aagye rhe
18/09/25, 23:16 - Umang Goyal: This message was deleted
18/09/25, 23:17 - Yogesh Agrawal: Tu Mt bol bich me
18/09/25, 23:19 - +91 92598 36859: Aeee tu kahase aaya beech m <This message was edited>
19/09/25, 16:03 - Damroo AA CE: Pcph class reschedule to 4 to 5pm
19/09/25, 20:33 - +91 97193 96608: Kiska hai aaj svar round
19/09/25, 20:34 - Krishna AA CE: Us!
19/09/25, 20:34 - +91 97193 96608: Aur koi
19/09/25, 20:35 - Shubh AA 2nd year GLA: Core walo ka?
19/09/25, 21:00 - +91 97193 96608: Join kr lo
19/09/25, 21:00 - +91 97193 96608: Jiska ho
19/09/25, 21:00 - +91 97193 96608: Start ho gya
19/09/25, 21:01 - +91 97193 96608: Hai
19/09/25, 21:01 - +91 76186 24348: Tere pe mail aaya h
19/09/25, 21:01 - +91 97193 96608: Hmm
19/09/25, 21:10 - +91 92598 36859: Chl rha h kya kisika?
19/09/25, 21:10 - +91 92598 36859: Mere m to nhi aa rha
19/09/25, 21:10 - +91 92598 36859: Kuch
19/09/25, 21:11 - +91 76186 24348: Nhi chal raha
19/09/25, 21:28 - Sandeep Solanki: Bhai apna toh ho gya
19/09/25, 21:28 - Sandeep Solanki: 😎
19/09/25, 21:28 - Shubh AA 2nd year GLA: Hn ho gya
19/09/25, 21:28 - +91 92598 36859: Kya hua tha?
19/09/25, 21:29 - +91 92598 36859: Mtlb kaise tha questions thy kya tha?
19/09/25, 21:29 - +91 74179 61902: Ho gya bhai
19/09/25, 21:29 - +91 74179 61902: Are kuch nhi
19/09/25, 21:29 - +91 74179 61902: 5-6 ques to dekhr sentence ko bolna tha
19/09/25, 21:29 - Sandeep Solanki: Aare kuch nhi
19/09/25, 21:29 - +91 74179 61902: 5-6 voice sunkr bolna tha
19/09/25, 21:29 - +91 97193 96608: This message was deleted
19/09/25, 21:29 - +91 74179 61902: 5-6 basic the
19/09/25, 21:29 - +91 92598 36859: Acchaaaa
19/09/25, 21:29 - Sandeep Solanki: Bs 2,4 que m Jo likha tha wo bolna tha
19/09/25, 21:29 - +91 92598 36859: Okk
19/09/25, 21:29 - +91 74179 61902: Planet wgra related
19/09/25, 21:29 - Sandeep Solanki: Or 2,4 m jumble words the
19/09/25, 21:29 - Sandeep Solanki: Basic tha bhot
19/09/25, 21:30 - +91 74179 61902: 5-6 jumble words the
19/09/25, 21:30 - +91 74179 61902: Bas
19/09/25, 21:34 - +91 92598 36859: 🤣🤣
19/09/25, 21:35 - Shubh AA 2nd year GLA: Kl company me baithega londa
19/09/25, 21:36 - Sandeep Solanki: Areee mere sherrrr 🐅
19/09/25, 21:37 - Sandeep Solanki: @⁨~Hani Chaudhary⁩ iske ghr bhjde y video
19/09/25, 21:37 - Sandeep Solanki: Ghr wale khush ho jynge ki ldka kuch toh krra hai 🤣🤣
19/09/25, 21:40 - Umang Goyal: This message was deleted
19/09/25, 21:40 - +91 82736 66361: Vo gande log se baat nahi karta
19/09/25, 21:40 - Umang Goyal: Play audio off hain
19/09/25, 21:41 - Umang Goyal: Dhek
19/09/25, 21:41 - Sandeep Solanki: Gussa ho gya hai syd
19/09/25, 21:41 - Umang Goyal: Sandeep tu  jake bol de <This message was edited>
19/09/25, 21:41 - +91 91931 01004: Sare
19/09/25, 21:42 - +91 74179 61902: 😂😂
19/09/25, 21:42 - Shubh AA 2nd year GLA: Ye Wale section me dikkat hai
19/09/25, 21:59 - Yogesh Agrawal: Result show ho rha h kisi ke pe
19/09/25, 22:10 - +91 91931 01004: This message was deleted
19/09/25, 22:30 - Shubh AA 2nd year GLA: Hn
19/09/25, 22:31 - Yogesh Agrawal: Dekh le to bta kyu rha h😂
19/09/25, 22:40 - Shubh AA 2nd year GLA: Dekh liya bc
21/09/25, 22:35 - Sameeraj AA EC: https://www.instagram.com/reel/DO0vDcyD-o8/?igsh=MWVsbXJobHNsbTgzOQ==
21/09/25, 23:39 - Sameeraj AA EC: Dubey correct konse hai har baat perplexity, Gemini ya ChatGPT
21/09/25, 23:40 - Sameeraj AA EC: Answers of weekly assignment
22/09/25, 09:30 - Sameeraj AA EC: https://www.instagram.com/reel/DO0bFMKEgtP/?igsh=MWp4a2Fqc3c4aDFnZA==
22/09/25, 13:40 - Sameeraj AA EC: Is to inform all of you that software engineering class has been cancelled
22/09/25, 13:40 - Sameeraj AA EC: Now if someone can help me with who is absent
22/09/25, 13:44 - Sameeraj AA EC: Tell me who is absent today I am going to send it within 6 minutes
22/09/25, 13:44 - Shubh AA 2nd year GLA: all present
22/09/25, 13:45 - Vinayak GLA 2nd Year: Koi apne iphone ka charger class ma bhul gaya tha
22/09/25, 14:20 - Damroo AA CE: week-10 answers
22/09/25, 14:20 - Damroo AA CE pinned a message
22/09/25, 14:21 - Sameeraj AA EC: @⁨Damroo AA CE⁩ mera assignment kar dena
22/09/25, 14:22 - Shubh AA 2nd year GLA: @⁨Sameeraj AA EC⁩ mera assignment kar dena
22/09/25, 17:54 - Aditya AA EC GLA: This message was deleted
22/09/25, 23:29 - Sameeraj AA EC: https://www.instagram.com/reel/DLudtXzIrcp/?igsh=MTB3aTJmbDg1NnNmaA==
23/09/25, 12:54 - +91 74179 61902: @⁨Damroo AA CE⁩ bhai verbal wale se sir se bat kr le 5-6 wali class agr 2-3 schedule ho jaye to..kyuki software wali legegi nhi ...isse achha batch 1 wale bacche 3 bje free ho jayengey <This message was edited>
23/09/25, 13:06 - Damroo AA CE: Mene sir ko call kiya lekin uthaya nhi unhone
23/09/25, 13:21 - PIYUSH SHARMA: Kisne beja h ye ?
23/09/25, 13:21 - Aditya AA EC GLA: Section B p aya th to send kr diya
23/09/25, 13:21 - Sameeraj AA EC: I think Quazi Ziauddin
23/09/25, 13:22 - Sameeraj AA EC: Verbal ka hai
23/09/25, 13:22 - Sameeraj AA EC: Oh
23/09/25, 13:41 - Vinayak GLA 2nd Year: Hello
23/09/25, 13:41 - Vinayak GLA 2nd Year: Bhai jo a2 wala hai
23/09/25, 13:41 - Vinayak GLA 2nd Year: Kon kon aaya hai
23/09/25, 13:41 - Vinayak GLA 2nd Year: Osma
23/09/25, 13:41 - Vinayak GLA 2nd Year: Apna apna roll no bata do
23/09/25, 13:41 - Vinayak GLA 2nd Year: Jo aaya hai
23/09/25, 13:42 - Yogesh Agrawal: Kyu
23/09/25, 13:42 - PIYUSH SHARMA: Absent puchna Vinayak
23/09/25, 13:42 - Umang Goyal: Lab nhi hain kya
23/09/25, 13:44 - +91 92598 36859: Bhai meri sachin ki or Shivam chaudhary ki present rhegi
23/09/25, 13:44 - +91 97581 09816: Bhai 49 present
23/09/25, 13:44 - +91 92598 36859: 34,38,39 present
23/09/25, 13:45 - saurabh ECE GLA: 37 present <This message was edited>
23/09/25, 13:45 - Umang Goyal: 45 present
23/09/25, 13:46 - rOnak GLA EC: 32,33 present
23/09/25, 13:46 - Yogesh Agrawal: 27 to 52 all present
23/09/25, 13:47 - Umang Goyal: This message was deleted
23/09/25, 13:53 - Vinayak GLA 2nd Year: Bhai agar class cancel hone bali hogi to bhi cancel nhi hogi
23/09/25, 14:03 - Vinayak GLA 2nd Year: Bhai 3 baja
23/09/25, 14:03 - Vinayak GLA 2nd Year: 2 min ka liya lab ma aa jana
23/09/25, 14:03 - Vinayak GLA 2nd Year: Sir attendance la ker jaana denga
23/09/25, 14:03 - PIYUSH SHARMA: Ok
23/09/25, 14:04 - +91 96750 87197: Roll no 15,22
23/09/25, 14:10 - Sameeraj AA EC: Roll no. 35 present
23/09/25, 14:11 - Upanshu Nayak AA CE: Aajana bhai bs 2 min ke liye attendance lagwakar chlejaana
23/09/25, 14:12 - Sameeraj AA EC: Kab aana hai
23/09/25, 14:12 - Upanshu Nayak AA CE: 3 bje
23/09/25, 14:12 - Upanshu Nayak AA CE: Jis jiski devarishi sir ki lab ho
23/09/25, 14:13 - Vinayak GLA 2nd Year: Osko 3 baja Anna hai
23/09/25, 14:13 - Vinayak GLA 2nd Year: Sir attendance ka liya bula raha hai bas
23/09/25, 14:20 - Krishna AA CE: This message was deleted
23/09/25, 15:00 - Vinayak GLA 2nd Year: Verbal class cancle
23/09/25, 15:00 - Vinayak GLA 2nd Year: Sir ka pass attendance baj di
23/09/25, 15:01 - +91 90768 32806: All present hai na
23/09/25, 15:02 - +91 78604 08855: Tu absent h
23/09/25, 15:02 - +91 90768 32806: Kyu
23/09/25, 15:04 - +91 78604 08855: Clg aa chup chap
23/09/25, 17:28 - Damroo AA CE:
23/09/25, 17:30 - Damroo AA CE: Thanks @⁨Pankaj Singh Rawat⁩ Notes ke liye
23/09/25, 17:35 - Aditya AA EC GLA: 🎉🎉
23/09/25, 17:35 - +91 89235 30004: 🫂♥️
23/09/25, 17:35 - Sameeraj AA EC: @⁨Pankaj Singh Rawat⁩ Thanks Bhai
23/09/25, 17:36 - Pankaj Singh Rawat: <Media omitted>
23/09/25, 18:39 - Vinayak GLA 2nd Year: @⁨Pankaj Singh Rawat⁩
23/09/25, 18:45 - +91 92598 36859: <Media omitted>
23/09/25, 18:45 - +91 92598 36859: @⁨Pankaj Singh Rawat⁩
24/09/25, 10:45 - Aditya AA EC GLA: https://www.instagram.com/reel/DM7a_9xxq9j/?igsh=MWgwNHUwYjM5MGw2aw==
24/09/25, 10:55 - +91 79832 20953 joined using a group link.
24/09/25, 12:01 - +91 788 725 2559: This message was deleted
24/09/25, 12:15 - Umang Goyal: This message was deleted
24/09/25, 12:16 - Shubh AA 2nd year GLA: Aaja
24/09/25, 12:17 - Umang Goyal: This message was deleted
25/09/25, 10:33 - Krishna AA CE: India president at Mathura Junction Railway Station!
25/09/25, 12:40 - Shubh AA 2nd year GLA: Profit and loss sheet ke soln bhejna
25/09/25, 13:41 - +91 92169 86867: https://www.instagram.com/reel/DO_gAH3EvN-/?igsh=NDBkc3kxdXYxbDEw
25/09/25, 13:46 - +91 92598 36859: Cheeteh❤️
25/09/25, 15:26 - Krishna AA CE: श्री द्रोपदी मुर्मू जी का मथुरा वृन्दावन में आगमन।।
25/09/25, 15:30 - Damroo AA CE:
25/09/25, 15:34 - +91 79832 20953: Dubay bhai type 4 ka  3 , 4 and 5ka solution bhej de
25/09/25, 15:34 - +91 79832 20953: Profit and loss ke
25/09/25, 18:24 - +91 92598 36859: Verbal k bhi koi notes h kya kisipe?
25/09/25, 18:26 - +91 92598 36859: Bss itne hi h?
25/09/25, 18:27 - +91 89235 30004: Mere hisab se :-
Tenses
Subject verb agreement
Orr y sheet 2 k words practice krr lena
25/09/25, 18:27 - +91 92598 36859: Okay
25/09/25, 18:27 - +91 89235 30004: 💦🥵
25/09/25, 22:00 - +91 74179 61902: Bhai kisi pe verbal wali sheets ke solutions hain kya ??
25/09/25, 22:29 - +91 74179 61902: Thankyou bhai
25/09/25, 22:29 - Yogesh Agrawal: This message was deleted
25/09/25, 22:29 - +91 74179 61902: Bas 4th glt hai
25/09/25, 22:29 - +91 74179 61902: Highlight ho to rhe hain
26/09/25, 00:19 - +91 95551 18785: Bhaii... Ye coding & decoding me Not, Can't be determined, and none of these wale options kb kb valid hote hai
26/09/25, 00:19 - +91 95551 18785: Koii batado
26/09/25, 00:24 - +91 78604 08855: None of these - jab answer option me na ho....
Can't be determined - jb answer nhi nikal skte
26/09/25, 08:21 - Aditya AA EC GLA: Ab 8 mai hai na exam...??
26/09/25, 08:30 - Vinayak GLA 2nd Year: Haa
26/09/25, 08:32 - Gaurav Gautam GLA: Sitting plan h kisi p
26/09/25, 08:32 - Vinayak GLA 2nd Year: Bhai vo abhi udhar bhu nahi laga hoga
26/09/25, 09:02 - +91 95061 15183: This message was deleted
28/09/25, 10:57 - +91 85338 44236: This message was deleted
28/09/25, 22:40 - Damroo AA CE: YE ISLIYE BHEJA HE JISKO THEORY YA ANSWER FORMATION ME PROBLEM AA RAHI HO ISSME SE DEKHLO SHAAYAD KUCH WORDS KI  HELP MILJAYE
28/09/25, 22:41 - +91 92598 36859: Aree dobay ji gussa nhi
28/09/25, 22:41 - +91 92598 36859: Dubay*
29/09/25, 00:17 - Aditya AA EC GLA:
29/09/25, 13:54 - Aditya AA EC GLA: Mam n jo likhavaya hai imp usko phle Krna y bad m
29/09/25, 13:55 - Aditya AA EC GLA: Mam k imp likhvaya hua... topic bhej do koi..
29/09/25, 15:28 - Damroo AA CE: .
29/09/25, 19:45 - +91 82736 66361: Previous year paper bhej do vlsi ka
29/09/25, 20:14 - Damroo AA CE: This message was deleted
29/09/25, 20:17 - Aditya AA EC GLA: Bhai solution...?
29/09/25, 20:17 - Damroo AA CE: VO TO MERE BHI NHI HUE😅😅
29/09/25, 20:18 - +91 97193 96608: Kitna padega cr bhai
29/09/25, 20:18 - Aditya AA EC GLA: Padhta to solution thode mang rha hota...najar lga do 🙂
29/09/25, 20:19 - Aditya AA EC GLA: Kosis kr aaaajye...tb bhej dena
29/09/25, 20:19 - +91 97193 96608: Yah baccho ko syllabus pata nahi chal paa rahahai tum pyq pad Rahe ho
29/09/25, 20:20 - Aditya AA EC GLA: Sb afva hai...exam dekho 😂
29/09/25, 20:21 - +91 97193 96608: Kl dekh hi lenge😂😂 <This message was edited>
29/09/25, 21:20 - Shubh AA 2nd year GLA: 2024-25 ka mid hai?
30/09/25, 15:27 - Damroo AA CE: Bhai 1st oct last date he week-10 ki
30/09/25, 16:06 - Damroo AA CE: Software engineering notes
30/09/25, 16:06 - Damroo AA CE pinned a message
30/09/25, 19:59 - Sandeep Solanki: Bhai kisi k ps software engineering k imp topics likhre ho aache se toh bhjdo bhai
01/10/25, 11:17 - Damroo AA CE: yellow esme important highlighted hai
01/10/25, 11:18 - Damroo AA CE: Aaj week-10 ki last date he jinka nhi hua vo karlo
01/10/25, 21:04 - Yogesh Agrawal pinned a message
01/10/25, 22:53 - Vinayak GLA 2nd Year: Function point numerical
Requirement engineering
SRS
ROLE OF SOFTWARE
SRS COMPONENTS Design
USE CASE DIAGRAM
02/10/25, 17:52 - +91 96750 87197: software ka previous year ho too send kr do koi.
02/10/25, 21:05 - Yogesh Agrawal pinned a message
03/10/25, 22:34 - Damroo AA CE: Practice assignment questions for theory related queries

Coding questions - if not affluent with coding syntax then you can write algorithms or pseudocode, if confident, you can write your answers in any language you're comfortable with as long as the logic is correct.
03/10/25, 22:35 - Damroo AA CE: instruction given by mam
03/10/25, 22:35 - +91 91931 01004: Bhai theory kitne no ki ayegi
03/10/25, 22:35 - +91 91931 01004: Ye puch lo ek barr
03/10/25, 22:36 - Damroo AA CE: bhai yeh nhi bataya unhone
03/10/25, 22:36 - +91 91931 01004: Bhai ek bar bat kar ke puch lo mam se
03/10/25, 22:36 - Damroo AA CE: mujhe jaisa lagta he theory thodi jayanda rahegi aur code ke saath explain karna padega

In [5]:
pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [8]:
messages = re.split(pattern, data)[1:]
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*\n',
 'Aditya AA EC GLA: Communication k assignment hogyaa kisika...?\n',
 'Vinayak GLA 2nd Year: Yes\n',
 '+91 788 725 2559: Bhej do\n',
 '+91 84398 26596: Bhjo\n',
 '+91 90768 32806: Bhejo\n',
 'Aditya AA EC GLA: Aaj bhi quiz h kyaa...?\n',
 'Shubh AA 2nd year GLA: Nhi\n',
 'Damroo AA CE: Quiz chalu hone vali he 10bje se Vlsi ki\n',
 '+91 76186 24348: Answer bhej do\n',
 'Vinayak GLA 2nd Year: \n',
 'Umang Goyal: Kitne hue sahi\n',
 'Damroo AA CE: Ye lo pure 20 ke 20 sahi he\n',
 'Sandeep Solanki: Hein\n',
 'Sandeep Solanki: Tune save and next nhi kre ky\n',
 'Umang Goyal: Are\n',
 'Shubh AA 2nd year GLA: Saare save kiye the\n',
 'Shubh AA 2nd year GLA: Hn\n',
 'Sandeep Solanki: Upr se hi switch kre hain ky\n',
 'Sandeep Solanki: Aare\n',
 'Shubh AA 2nd year GLA: Nhi\n',
 'Sandeep Solanki: Chud gye guru tum toh\n',
 'Shubh AA 2nd year GLA: Pehli baar thodi de raha hu\n',
 'Sandeep Solanki: Mdm ko inform krde\n',
 'Sandeep Solanki: Abhi turant\n',
 'Shubh AA 2nd year GLA: Hn\n',
 '+91 97193 96608: Waw cr\n',
 'Shubh AA 2nd year GLA: Bhai kisi ka verilog ka assignment ho gya ho toh bhej do\n',
 'Vinayak GLA 2nd Year: Bhai baj do koi\n',
 'Yogesh Agrawal: Quiz active ho gya h D.comm ka\n',
 'Upanshu Nayak AA CE: Answer bhejdo\n',
 'Yogesh Agrawal: Yes koi answers bhej do\n',
 'Upanshu Nayak AA CE: Answer\n',
 '+91 91701 56635: Bhai answer bhej do kui\n',
 '+91 85338 44236: \n',
 '+91 85338 44236: Bhai log usme 8 shi h\n',
 'Yogesh Agrawal: Ha hme dikh rha h\n',
 'Umang Goyal: 10 ka c bhi nhi hajn\n',
 'Umang Goyal: Hain\n',
 '+91 90272 00819: D hai 10 ka\n',
 'Umang Goyal: 3 ka b bhi nhi hain\n',
 'Vinayak GLA 2nd Year: Bhai verilog ka assignment baj do koi\n',
 '+91 85338 44236: Hnn woh muje ptaa h....sbbko dikh rha h\n...tere jeso ke liye hi likha tha.... chlo shi h phir tujhe dikh rha h toh\n',
 'Damroo AA CE pinned a message\n',
 'Damroo AA CE: Last date is 17th september\n',
 '+91 84398 26596: H ky ye?\n',
 'Damroo AA CE: Nptel project management for mangers week-8 Answers\n',
 '+91 78190 09204: Bhai Verilog ka assignment bhej do koi\n',
 'Sameeraj AA EC: https://www.instagram.com/reel/DOdyo7tCFIS/?igsh=OXd6Ymp1dnlibDE2\n',
 'Aditya AA EC GLA: <Media omitted>\n',
 '+91 788 725 2559: https://youtu.be/tDN3cdFUatM?si=rJjt6burAr3c1FhG\n',
 '+91 90272 00819: https://youtube.com/shorts/MMf9Y2lMbDQ?si=Mb3SHTTZ1xjyMlnd\n',
 'Sameeraj AA EC: https://www.instagram.com/reel/DOJK4fmjDv-/?igsh=aDlpaWp1dng4czE=\n',
 'Damroo AA CE: \n',
 'Aditya AA EC GLA: 4 glt hai isme\n',
 'Shubh AA 2nd year GLA: Konse\n',
 'Aditya AA EC GLA: Dundh le khud\n',
 'Sameeraj AA EC: @\u2068Shubh AA 2nd year GLA\u2069\n',
 'Sameeraj AA EC: Abhi submit kar karna\n',
 'Shubh AA 2nd year GLA: Kya\n',
 'Sandeep Solanki: Aare quiz hai quiz dede\n',
 'Damroo AA CE: DBLnv3B9t3HdfpY493QNXQ==.pdf https://share.google/fyly9L49rwPJDOF3W\n',
 'Aditya AA EC GLA: 2-3 class cancel hai...mam nhi aarhe... tbiyat khrab hone h vjh s to...awaz mt Krna k baki koi aur teacher aajye sab dekh k...\n',
 'Shubh AA 2nd year GLA: Present laga diyo\n',
 'Shubh AA 2nd year GLA: 30, 41 and 25 yaha se\n',
 'Aditya AA EC GLA: Bhailog class cancel nhi hai...bss mam present nhi hai...halla mt kro k koi aur teacher aajye... unka name p bhi aajyege baat aur hamra bhi lanka lgege\n',
 '+91 90768 32806: 13 ec cs pe bhi present laga diyo\n',
 '+91 788 725 2559: 11 ec cs\n',
 '+91 788 725 2559: Mere bhi laga dena\n',
 '+91 89603 78812: 08 ec CS also present\n',
 'Damroo AA CE: Channel Length Modulation (CLM) in MOSFET is kind of like what happens when you pinch a water pipe:\n\nNormally, when a MOSFET is in saturation, the current (Id) is supposed to be constant and not depend on drain voltage (Vds).\n\nBut in reality, as Vds increases, the depletion region at the drain expands and eats into the channel.\n\nThis makes the effective channel length shorter (like making the pipe shorter).\n\nShorter channel → less resistance → current increases slightly with Vds.\n\n\n👉 So, Channel Length Modulation means the drain current in saturation is not perfectly flat, but increases with drain voltage.\n\nIt’s modeled by adding a factor  to the current equation. <This message was edited>\n',
 'Damroo AA CE: aaj last date he week-8 ki\n',
 '+91 788 725 2559: https://youtu.be/Gq8M-dWL2pY?si=0CxQLDxYI2GlL4iD\n',
 'PIYUSH SHARMA: This message was deleted\n',
 '+91 63978 13356: Nhi Bhai😒\n',
 '+91 97612 84100: This message was deleted\n',
 '+91 63978 13356: This message was deleted\n',
 '+91 97612 84100: This message was deleted\n',
 'Aditya AA EC GLA removed Dev Mohan\n',
 '+91 74179 61902: Bhaiyo kisi ko agr ek black color ki plastic ki bottle mile to btana\n',
 '+91 92598 36859: Yele bhai\n',
 '+91 74179 61902: 😂\n',
 '+91 74179 61902: Kl de diyo bhai\n',
 '+91 92598 36859: Okk bhai\n',
 '+91 74179 61902: Hmm\n',
 '+91 97193 96608: https://www.instagram.com/reel/DOF93SEgL8A/?igsh=MWgzdzZ5aWRnNzZncw==\n',
 '+91 97193 96608: Aditya cr\n',
 'Umang Goyal: Nhi yogesh par sahi  baitha hai\n',
 'Damroo AA CE: Agar kisi ki 19th august me leave lagi ho batado verbal aptitude ki attendance bhejni he\n',
 'Upanshu Nayak AA CE: all present bhejdo!\n',
 '+91 92598 36859: Yess i support this statement\n',
 'Krishna AA CE: It is not possible!!\n',
 'Krishna AA CE: Please give your names if you have leave!\n',
 '+91 92598 36859: Mujhe sachin ko or shivam chaudhary ko present rkhna baaki mujhe frk nhi pdta\n',
 '+91 92598 36859: 34,39,38\n',
 'Krishna AA CE: Leave toh nhi h?\n',
 '+91 92598 36859: Nooo\n',
 '+91 89235 30004: 💦\n',
 'Sameeraj AA EC: Abe jisko absent karvani hai vo bol do baki sab present hai by default jisko dikkat hai apna khud dekh le\n',
 '+91 89235 30004: 👉🏻👌🏻💦\n',
 'Krishna AA CE: Bhai btado jiska bhi h!\n',
 '+91 92598 36859: Yogesh ko absent krdo\n',
 'Yogesh Agrawal: Kiyu\n',
 '+91 92598 36859: Ese hi\n',
 'Yogesh Agrawal: Ese hi tu fir kisi aur ka bhi name le skta h mera hi kyu liya\n',
 '+91 92598 36859: Kyuki tu bhaiii h\n',
 '+91 92598 36859: M cahata hu tu sb cheej m aagye rhe\n',
 'Umang Goyal: This message was deleted\n',
 'Yogesh Agrawal: Tu Mt bol bich me\n',
 '+91 92598 36859: Aeee tu kahase aaya beech m <This message was edited>\n',
 'Damroo AA CE: Pcph class reschedule to 4 to 5pm\n',
 '+91 97193 96608: Kiska hai aaj svar round\n',
 'Krishna AA CE: Us!\n',
 '+91 97193 96608: Aur koi\n',
 'Shubh AA 2nd year GLA: Core walo ka?\n',
 '+91 97193 96608: Join kr lo\n',
 '+91 97193 96608: Jiska ho\n',
 '+91 97193 96608: Start ho gya\n',
 '+91 97193 96608: Hai\n',
 '+91 76186 24348: Tere pe mail aaya h\n',
 '+91 97193 96608: Hmm\n',
 '+91 92598 36859: Chl rha h kya kisika?\n',
 '+91 92598 36859: Mere m to nhi aa rha\n',
 '+91 92598 36859: Kuch\n',
 '+91 76186 24348: Nhi chal raha\n',
 'Sandeep Solanki: Bhai apna toh ho gya\n',
 'Sandeep Solanki: 😎\n',
 'Shubh AA 2nd year GLA: Hn ho gya\n',
 '+91 92598 36859: Kya hua tha?\n',
 '+91 92598 36859: Mtlb kaise tha questions thy kya tha?\n',
 '+91 74179 61902: Ho gya bhai\n',
 '+91 74179 61902: Are kuch nhi\n',
 '+91 74179 61902: 5-6 ques to dekhr sentence ko bolna tha\n',
 'Sandeep Solanki: Aare kuch nhi\n',
 '+91 74179 61902: 5-6 voice sunkr bolna tha\n',
 '+91 97193 96608: This message was deleted\n',
 '+91 74179 61902: 5-6 basic the\n',
 '+91 92598 36859: Acchaaaa\n',
 'Sandeep Solanki: Bs 2,4 que m Jo likha tha wo bolna tha\n',
 '+91 92598 36859: Okk\n',
 '+91 74179 61902: Planet wgra related\n',
 'Sandeep Solanki: Or 2,4 m jumble words the\n',
 'Sandeep Solanki: Basic tha bhot\n',
 '+91 74179 61902: 5-6 jumble words the\n',
 '+91 74179 61902: Bas\n',
 '+91 92598 36859: 🤣🤣\n',
 'Shubh AA 2nd year GLA: Kl company me baithega londa\n',
 'Sandeep Solanki: Areee mere sherrrr 🐅\n',
 'Sandeep Solanki: @\u2068~Hani Chaudhary\u2069 iske ghr bhjde y video\n',
 'Sandeep Solanki: Ghr wale khush ho jynge ki ldka kuch toh krra hai 🤣🤣\n',
 'Umang Goyal: This message was deleted\n',
 '+91 82736 66361: Vo gande log se baat nahi karta\n',
 'Umang Goyal: Play audio off hain\n',
 'Umang Goyal: Dhek\n',
 'Sandeep Solanki: Gussa ho gya hai syd\n',
 'Umang Goyal: Sandeep tu  jake bol de <This message was edited>\n',
 '+91 91931 01004: Sare\n',
 '+91 74179 61902: 😂😂\n',
 'Shubh AA 2nd year GLA: Ye Wale section me dikkat hai\n',
 'Yogesh Agrawal: Result show ho rha h kisi ke pe\n',
 '+91 91931 01004: This message was deleted\n',
 'Shubh AA 2nd year GLA: Hn\n',
 'Yogesh Agrawal: Dekh le to bta kyu rha h😂\n',
 'Shubh AA 2nd year GLA: Dekh liya bc\n',
 'Sameeraj AA EC: https://www.instagram.com/reel/DO0vDcyD-o8/?igsh=MWVsbXJobHNsbTgzOQ==\n',
 'Sameeraj AA EC: Dubey correct konse hai har baat perplexity, Gemini ya ChatGPT\n',
 'Sameeraj AA EC: Answers of weekly assignment\n',
 'Sameeraj AA EC: https://www.instagram.com/reel/DO0bFMKEgtP/?igsh=MWp4a2Fqc3c4aDFnZA==\n',
 'Sameeraj AA EC: Is to inform all of you that software engineering class has been cancelled\n',
 'Sameeraj AA EC: Now if someone can help me with who is absent\n',
 'Sameeraj AA EC: Tell me who is absent today I am going to send it within 6 minutes\n',
 'Shubh AA 2nd year GLA: all present\n',
 'Vinayak GLA 2nd Year: Koi apne iphone ka charger class ma bhul gaya tha\n',
 'Damroo AA CE: week-10 answers\n',
 'Damroo AA CE pinned a message\n',
 'Sameeraj AA EC: @\u2068Damroo AA CE\u2069 mera assignment kar dena\n',
 'Shubh AA 2nd year GLA: @\u2068Sameeraj AA EC\u2069 mera assignment kar dena\n',
 'Aditya AA EC GLA: This message was deleted\n',
 'Sameeraj AA EC: https://www.instagram.com/reel/DLudtXzIrcp/?igsh=MTB3aTJmbDg1NnNmaA==\n',
 '+91 74179 61902: @\u2068Damroo AA CE\u2069 bhai verbal wale se sir se bat kr le 5-6 wali class agr 2-3 schedule ho jaye to..kyuki software wali legegi nhi ...isse achha batch 1 wale bacche 3 bje free ho jayengey <This message was edited>\n',
 'Damroo AA CE: Mene sir ko call kiya lekin uthaya nhi unhone\n',
 'PIYUSH SHARMA: Kisne beja h ye ?\n',
 'Aditya AA EC GLA: Section B p aya th to send kr diya\n',
 'Sameeraj AA EC: I think Quazi Ziauddin\n',
 'Sameeraj AA EC: Verbal ka hai\n',
 'Sameeraj AA EC: Oh\n',
 'Vinayak GLA 2nd Year: Hello\n',
 'Vinayak GLA 2nd Year: Bhai jo a2 wala hai\n',
 'Vinayak GLA 2nd Year: Kon kon aaya hai\n',
 'Vinayak GLA 2nd Year: Osma\n',
 'Vinayak GLA 2nd Year: Apna apna roll no bata do\n',
 'Vinayak GLA 2nd Year: Jo aaya hai\n',
 'Yogesh Agrawal: Kyu\n',
 'PIYUSH SHARMA: Absent puchna Vinayak\n',
 'Umang Goyal: Lab nhi hain kya\n',
 '+91 92598 36859: Bhai meri sachin ki or Shivam chaudhary ki present rhegi\n',
 '+91 97581 09816: Bhai 49 present\n',
 '+91 92598 36859: 34,38,39 present\n',
 'saurabh ECE GLA: 37 present <This message was edited>\n',
 'Umang Goyal: 45 present\n',
 'rOnak GLA EC: 32,33 present\n',
 'Yogesh Agrawal: 27 to 52 all present\n',
 'Umang Goyal: This message was deleted\n',
 'Vinayak GLA 2nd Year: Bhai agar class cancel hone bali hogi to bhi cancel nhi hogi\n',
 'Vinayak GLA 2nd Year: Bhai 3 baja\n',
 'Vinayak GLA 2nd Year: 2 min ka liya lab ma aa jana\n',
 'Vinayak GLA 2nd Year: Sir attendance la ker jaana denga\n',
 'PIYUSH SHARMA: Ok\n',
 '+91 96750 87197: Roll no 15,22\n',
 'Sameeraj AA EC: Roll no. 35 present\n',
 'Upanshu Nayak AA CE: Aajana bhai bs 2 min ke liye attendance lagwakar chlejaana\n',
 'Sameeraj AA EC: Kab aana hai\n',
 'Upanshu Nayak AA CE: 3 bje\n',
 'Upanshu Nayak AA CE: Jis jiski devarishi sir ki lab ho\n',
 'Vinayak GLA 2nd Year: Osko 3 baja Anna hai\n',
 'Vinayak GLA 2nd Year: Sir attendance ka liya bula raha hai bas\n',
 'Krishna AA CE: This message was deleted\n',
 'Vinayak GLA 2nd Year: Verbal class cancle\n',
 'Vinayak GLA 2nd Year: Sir ka pass attendance baj di\n',
 '+91 90768 32806: All present hai na\n',
 '+91 78604 08855: Tu absent h\n',
 '+91 90768 32806: Kyu\n',
 '+91 78604 08855: Clg aa chup chap\n',
 'Damroo AA CE: \n',
 'Damroo AA CE: Thanks @\u2068Pankaj Singh Rawat\u2069 Notes ke liye\n',
 'Aditya AA EC GLA: 🎉🎉\n',
 '+91 89235 30004: 🫂♥️\n',
 'Sameeraj AA EC: @\u2068Pankaj Singh Rawat\u2069 Thanks Bhai\n',
 'Pankaj Singh Rawat: <Media omitted>\n',
 'Vinayak GLA 2nd Year: @\u2068Pankaj Singh Rawat\u2069\n',
 '+91 92598 36859: <Media omitted>\n',
 '+91 92598 36859: @\u2068Pankaj Singh Rawat\u2069\n',
 'Aditya AA EC GLA: https://www.instagram.com/reel/DM7a_9xxq9j/?igsh=MWgwNHUwYjM5MGw2aw==\n',
 '+91 79832 20953 joined using a group link.\n',
 '+91 788 725 2559: This message was deleted\n',
 'Umang Goyal: This message was deleted\n',
 'Shubh AA 2nd year GLA: Aaja\n',
 'Umang Goyal: This message was deleted\n',
 'Krishna AA CE: India president at Mathura Junction Railway Station!\n',
 'Shubh AA 2nd year GLA: Profit and loss sheet ke soln bhejna\n',
 '+91 92169 86867: https://www.instagram.com/reel/DO_gAH3EvN-/?igsh=NDBkc3kxdXYxbDEw\n',
 '+91 92598 36859: Cheeteh❤️\n',
 'Krishna AA CE: श्री द्रोपदी मुर्मू जी का मथुरा वृन्दावन में आगमन।।\n',
 'Damroo AA CE: \n',
 '+91 79832 20953: Dubay bhai type 4 ka  3 , 4 and 5ka solution bhej de\n',
 '+91 79832 20953: Profit and loss ke\n',
 '+91 92598 36859: Verbal k bhi koi notes h kya kisipe?\n',
 '+91 92598 36859: Bss itne hi h?\n',
 '+91 89235 30004: Mere hisab se :-\nTenses \nSubject verb agreement \nOrr y sheet 2 k words practice krr lena\n',
 '+91 92598 36859: Okay\n',
 '+91 89235 30004: 💦🥵\n',
 '+91 74179 61902: Bhai kisi pe verbal wali sheets ke solutions hain kya ??\n',
 '+91 74179 61902: Thankyou bhai\n',
 'Yogesh Agrawal: This message was deleted\n',
 '+91 74179 61902: Bas 4th glt hai\n',
 '+91 74179 61902: Highlight ho to rhe hain\n',
 "+91 95551 18785: Bhaii... Ye coding & decoding me Not, Can't be determined, and none of these wale options kb kb valid hote hai\n",
 '+91 95551 18785: Koii batado\n',
 "+91 78604 08855: None of these - jab answer option me na ho....\nCan't be determined - jb answer nhi nikal skte\n",
 'Aditya AA EC GLA: Ab 8 mai hai na exam...??\n',
 'Vinayak GLA 2nd Year: Haa\n',
 'Gaurav Gautam GLA: Sitting plan h kisi p\n',
 'Vinayak GLA 2nd Year: Bhai vo abhi udhar bhu nahi laga hoga\n',
 '+91 95061 15183: This message was deleted\n',
 '+91 85338 44236: This message was deleted\n',
 'Damroo AA CE: YE ISLIYE BHEJA HE JISKO THEORY YA ANSWER FORMATION ME PROBLEM AA RAHI HO ISSME SE DEKHLO SHAAYAD KUCH WORDS KI  HELP MILJAYE\n',
 '+91 92598 36859: Aree dobay ji gussa nhi\n',
 '+91 92598 36859: Dubay*\n',
 'Aditya AA EC GLA: \n',
 'Aditya AA EC GLA: Mam n jo likhavaya hai imp usko phle Krna y bad m\n',
 'Aditya AA EC GLA: Mam k imp likhvaya hua... topic bhej do koi..\n',
 'Damroo AA CE: .\n',
 '+91 82736 66361: Previous year paper bhej do vlsi ka\n',
 'Damroo AA CE: This message was deleted\n',
 'Aditya AA EC GLA: Bhai solution...?\n',
 'Damroo AA CE: VO TO MERE BHI NHI HUE😅😅\n',
 '+91 97193 96608: Kitna padega cr bhai\n',
 'Aditya AA EC GLA: Padhta to solution thode mang rha hota...najar lga do 🙂\n',
 'Aditya AA EC GLA: Kosis kr aaaajye...tb bhej dena\n',
 '+91 97193 96608: Yah baccho ko syllabus pata nahi chal paa rahahai tum pyq pad Rahe ho\n',
 'Aditya AA EC GLA: Sb afva hai...exam dekho 😂\n',
 '+91 97193 96608: Kl dekh hi lenge😂😂 <This message was edited>\n',
 'Shubh AA 2nd year GLA: 2024-25 ka mid hai?\n',
 'Damroo AA CE: Bhai 1st oct last date he week-10 ki\n',
 'Damroo AA CE: Software engineering notes\n',
 'Damroo AA CE pinned a message\n',
 'Sandeep Solanki: Bhai kisi k ps software engineering k imp topics likhre ho aache se toh bhjdo bhai\n',
 'Damroo AA CE: yellow esme important highlighted hai\n',
 'Damroo AA CE: Aaj week-10 ki last date he jinka nhi hua vo karlo\n',
 'Yogesh Agrawal pinned a message\n',
 'Vinayak GLA 2nd Year: Function point numerical\nRequirement engineering\nSRS\nROLE OF SOFTWARE\nSRS COMPONENTS Design\nUSE CASE DIAGRAM\n',
 '+91 96750 87197: software ka previous year ho too send kr do koi.\n',
 'Yogesh Agrawal pinned a message\n',
 "Damroo AA CE: Practice assignment questions for theory related queries \n\nCoding questions - if not affluent with coding syntax then you can write algorithms or pseudocode, if confident, you can write your answers in any language you're comfortable with as long as the logic is correct.\n",
 'Damroo AA CE: instruction given by mam\n',
 '+91 91931 01004: Bhai theory kitne no ki ayegi\n',
 '+91 91931 01004: Ye puch lo ek barr\n',
 'Damroo AA CE: bhai yeh nhi bataya unhone\n',
 '+91 91931 01004: Bhai ek bar bat kar ke puch lo mam se\n',
 'Damroo AA CE: mujhe jaisa lagta he theory thodi jayanda rahegi aur code ke saath explain karna padega\n',
 'Damroo AA CE: jaha pe jarrorat he\n',
 'Damroo AA CE: aur language koi bhi kar sakte ho\n',
 'Damroo AA CE: Assignment questions\n',
 '+91 90768 32806: Bhai inke answer ki pdf bhej do\n',
 'Damroo AA CE: location bhejdena kal\n',
 'Krishna AA CE: Read this\n',
 'Krishna AA CE: Everything mentioned in thiS\n',
 'Sameeraj AA EC: Not trying to sound fuzzy but\nHe said: location bhej dena _kal_\n',
 "Sameeraj AA EC: He's mentioning his habit of forgetting. What he meant was just remind him tomorrow\n",
 'Krishna AA CE: Bhai BTech kar rhe ho? N?\n',
 'Krishna AA CE: Okay no issues I will share the location\n',
 'Krishna AA CE: https://maps.app.goo.gl/DzNG2awcuuhrVQPAA?g_st=awb\n',
 'Sameeraj AA EC: https://www.instagram.com/reel/DPZBka1EaDp/?igsh=N2twbTN6YW9ydzY5\n',
 '+91 96750 87197: Bhai konsi date sheet sahi hai 💦\n',
 '+91 89235 30004: Oooo ri maiya 😮\n',
 'Umang Goyal: Ye hain\n',
 '+91 89235 30004: Sare tu bss datesheet dekhte rahio\nPadhio mtt\n',
 '+91 89235 30004: Heina\n',
 '+91 96750 87197: 😂😂\n',
 '+91 89603 78812: Ye wali\n',
 '+91 96750 87197: Haann\n',
 '+91 96750 87197: Smjh hi naa aarhi kaa padno hai\n',
 '+91 74179 61902: ...\n',
 '+91 74179 61902: Koi ppr puch lo yrr\n',
 '+91 74179 61902: CR bhai kro kuch jugad\n',
 '+91 89235 30004: 🥺\n',
 '+91 74179 61902: @\u2068Aditya AA EC GLA\u2069 bhaiiiiiiiiiiiiiii\n',
 '+91 96750 87197: 🫦🥵💦\n',
 '+91 96750 87197: Yaaa\n',
 '+91 74179 61902: We need u\n',
 '+91 96750 87197: Karoo naa\n',
 '+91 96750 87197: Kch jugad\n',
 '+91 74179 61902: Areeeeee deepak\n',
 '+91 74179 61902: Acha acha jugad\n',
 'Shubh AA 2nd year GLA: Bhai aaram se\n',
 '+91 74179 61902: Aese mt bolo\n',
 '+91 96750 87197: 😂🤣\n',
 '+91 89235 30004: Areey bhaiya Deepak ki le lena but krr lo\n',
 '+91 74179 61902: Bhai kuch kro\n',
 '+91 74179 61902: 60ques na rate jare\n',
 '+91 96750 87197: 💧\n',
 '+91 89235 30004: 😳\n',
 '+91 96750 87197: Bhai mere too smjh se bhara hai\n',
 '+91 74179 61902: Hn yrr 😭\n',
 '+91 96750 87197: \n',
 '+91 74179 61902: Imkc ye alg hi ghpla hai codes ka 🙂\n',
 '+91 96750 87197: 🥲\n',
 '+91 74179 61902: Shreshtha mam bich raate mein sath chod gyi 🥲\n',
 '+91 96750 87197: Mam 😭\n',
 '+91 74179 61902: Bhai iska koi ss leke mt bhej dena\n',
 '+91 74179 61902: Dar lgta hai ab 😭\n',
 '+91 96750 87197: Hmari gnd fat rhi h 😭\n',
 '+91 74179 61902: Aleleee mela bby 🫂\n',
 'Shubh AA 2nd year GLA: Na yaha koi itna toh dogla nhi I guess\n',
 '+91 96750 87197: Thank you Bbu💦\n',
 '+91 74179 61902: Urrre\n',
 'Aditya AA EC GLA: Sb isse chakar m to suru hua tha\n',
 '+91 74179 61902: Bas bas jyda aage mt bhade bhaiya\n',
 '+91 96750 87197: Aree too ss ka kiya krega koi hum apna duk bhi nahi batt skte kya bhai 🥲\n',
 '+91 74179 61902: Are bhai blkl\n',
 '+91 74179 61902: But kuch madarchod types of persons hain EC mein\n',
 '+91 96750 87197: Ab gnd fat rhi h too fat rhi hai ismai koi ss or lele\n',
 '+91 74179 61902: Jinki wkj se aaj aese bethna pd rh ahi\n',
 '+91 74179 61902: Hai*\n',
 '+91 74179 61902: Vrna ppr hath mein hota bhenchod\n',
 '+91 96750 87197: Acha\n',
 '+91 96750 87197: Haa yaarrrr\n',
 '+91 96750 87197: Chlo kholte hai copy bagera thodi bhot\n',
 '+91 74179 61902: Kya khol rh hai\n',
 '+91 74179 61902: Acha copy\n',
 '+91 74179 61902: Thk hai thk hai\n',
 '+91 96750 87197: Bbu coy\n',
 '+91 96750 87197: Cpoy\n',
 '+91 74179 61902: Notes complete honge tere to\n',
 '+91 74179 61902: Hai n\n',
 '+91 96750 87197: Copy\n',

In [10]:
dates = re.findall(pattern, data)
dates

['12/09/25, 16:04 - ',
 '12/09/25, 20:34 - ',
 '12/09/25, 20:40 - ',
 '12/09/25, 20:53 - ',
 '12/09/25, 20:53 - ',
 '12/09/25, 20:56 - ',
 '12/09/25, 20:59 - ',
 '12/09/25, 20:59 - ',
 '13/09/25, 09:56 - ',
 '13/09/25, 10:07 - ',
 '13/09/25, 10:08 - ',
 '13/09/25, 10:09 - ',
 '13/09/25, 10:11 - ',
 '13/09/25, 10:19 - ',
 '13/09/25, 10:19 - ',
 '13/09/25, 10:19 - ',
 '13/09/25, 10:19 - ',
 '13/09/25, 10:19 - ',
 '13/09/25, 10:19 - ',
 '13/09/25, 10:20 - ',
 '13/09/25, 10:20 - ',
 '13/09/25, 10:20 - ',
 '13/09/25, 10:20 - ',
 '13/09/25, 10:20 - ',
 '13/09/25, 10:20 - ',
 '13/09/25, 10:21 - ',
 '13/09/25, 10:22 - ',
 '13/09/25, 17:17 - ',
 '13/09/25, 17:18 - ',
 '13/09/25, 21:02 - ',
 '13/09/25, 21:02 - ',
 '13/09/25, 21:03 - ',
 '13/09/25, 21:05 - ',
 '13/09/25, 21:10 - ',
 '13/09/25, 21:11 - ',
 '13/09/25, 21:13 - ',
 '13/09/25, 21:13 - ',
 '13/09/25, 21:16 - ',
 '13/09/25, 21:16 - ',
 '13/09/25, 21:16 - ',
 '13/09/25, 21:17 - ',
 '13/09/25, 21:35 - ',
 '13/09/25, 23:38 - ',
 '14/09/25, 01:58 - ',
 '14/09/25, 01:59 - ',
 '14/09/25, 02:00 - ',
 '14/09/25, 02:00 - ',
 '14/09/25, 15:42 - ',
 '15/09/25, 12:15 - ',
 '15/09/25, 12:17 - ',
 '15/09/25, 15:47 - ',
 '15/09/25, 20:08 - ',
 '16/09/25, 00:22 - ',
 '16/09/25, 12:12 - ',
 '16/09/25, 12:14 - ',
 '16/09/25, 12:14 - ',
 '16/09/25, 12:14 - ',
 '16/09/25, 12:16 - ',
 '16/09/25, 12:16 - ',
 '16/09/25, 12:16 - ',
 '16/09/25, 12:18 - ',
 '17/09/25, 13:04 - ',
 '17/09/25, 14:17 - ',
 '17/09/25, 14:18 - ',
 '17/09/25, 14:18 - ',
 '17/09/25, 14:19 - ',
 '17/09/25, 14:26 - ',
 '17/09/25, 14:26 - ',
 '17/09/25, 14:27 - ',
 '17/09/25, 14:27 - ',
 '17/09/25, 15:27 - ',
 '17/09/25, 19:01 - ',
 '17/09/25, 22:24 - ',
 '18/09/25, 13:19 - ',
 '18/09/25, 13:20 - ',
 '18/09/25, 13:20 - ',
 '18/09/25, 13:21 - ',
 '18/09/25, 13:28 - ',
 '18/09/25, 15:40 - ',
 '18/09/25, 16:08 - ',
 '18/09/25, 16:43 - ',
 '18/09/25, 16:43 - ',
 '18/09/25, 16:43 - ',
 '18/09/25, 16:44 - ',
 '18/09/25, 16:44 - ',
 '18/09/25, 20:47 - ',
 '18/09/25, 20:47 - ',
 '18/09/25, 21:46 - ',
 '18/09/25, 22:24 - ',
 '18/09/25, 22:25 - ',
 '18/09/25, 22:25 - ',
 '18/09/25, 23:07 - ',
 '18/09/25, 23:08 - ',
 '18/09/25, 23:08 - ',
 '18/09/25, 23:08 - ',
 '18/09/25, 23:09 - ',
 '18/09/25, 23:09 - ',
 '18/09/25, 23:09 - ',
 '18/09/25, 23:09 - ',
 '18/09/25, 23:10 - ',
 '18/09/25, 23:10 - ',
 '18/09/25, 23:11 - ',
 '18/09/25, 23:12 - ',
 '18/09/25, 23:13 - ',
 '18/09/25, 23:14 - ',
 '18/09/25, 23:15 - ',
 '18/09/25, 23:15 - ',
 '18/09/25, 23:16 - ',
 '18/09/25, 23:17 - ',
 '18/09/25, 23:19 - ',
 '19/09/25, 16:03 - ',
 '19/09/25, 20:33 - ',
 '19/09/25, 20:34 - ',
 '19/09/25, 20:34 - ',
 '19/09/25, 20:35 - ',
 '19/09/25, 21:00 - ',
 '19/09/25, 21:00 - ',
 '19/09/25, 21:00 - ',
 '19/09/25, 21:01 - ',
 '19/09/25, 21:01 - ',
 '19/09/25, 21:01 - ',
 '19/09/25, 21:10 - ',
 '19/09/25, 21:10 - ',
 '19/09/25, 21:10 - ',
 '19/09/25, 21:11 - ',
 '19/09/25, 21:28 - ',
 '19/09/25, 21:28 - ',
 '19/09/25, 21:28 - ',
 '19/09/25, 21:28 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:29 - ',
 '19/09/25, 21:30 - ',
 '19/09/25, 21:30 - ',
 '19/09/25, 21:34 - ',
 '19/09/25, 21:35 - ',
 '19/09/25, 21:36 - ',
 '19/09/25, 21:37 - ',
 '19/09/25, 21:37 - ',
 '19/09/25, 21:40 - ',
 '19/09/25, 21:40 - ',
 '19/09/25, 21:40 - ',
 '19/09/25, 21:41 - ',
 '19/09/25, 21:41 - ',
 '19/09/25, 21:41 - ',
 '19/09/25, 21:41 - ',
 '19/09/25, 21:42 - ',
 '19/09/25, 21:42 - ',
 '19/09/25, 21:59 - ',
 '19/09/25, 22:10 - ',
 '19/09/25, 22:30 - ',
 '19/09/25, 22:31 - ',
 '19/09/25, 22:40 - ',
 '21/09/25, 22:35 - ',
 '21/09/25, 23:39 - ',
 '21/09/25, 23:40 - ',
 '22/09/25, 09:30 - ',
 '22/09/25, 13:40 - ',
 '22/09/25, 13:40 - ',
 '22/09/25, 13:44 - ',
 '22/09/25, 13:44 - ',
 '22/09/25, 13:45 - ',
 '22/09/25, 14:20 - ',
 '22/09/25, 14:20 - ',
 '22/09/25, 14:21 - ',
 '22/09/25, 14:22 - ',
 '22/09/25, 17:54 - ',
 '22/09/25, 23:29 - ',
 '23/09/25, 12:54 - ',
 '23/09/25, 13:06 - ',
 '23/09/25, 13:21 - ',
 '23/09/25, 13:21 - ',
 '23/09/25, 13:21 - ',
 '23/09/25, 13:22 - ',
 '23/09/25, 13:22 - ',
 '23/09/25, 13:41 - ',
 '23/09/25, 13:41 - ',
 '23/09/25, 13:41 - ',
 '23/09/25, 13:41 - ',
 '23/09/25, 13:41 - ',
 '23/09/25, 13:41 - ',
 '23/09/25, 13:42 - ',
 '23/09/25, 13:42 - ',
 '23/09/25, 13:42 - ',
 '23/09/25, 13:44 - ',
 '23/09/25, 13:44 - ',
 '23/09/25, 13:44 - ',
 '23/09/25, 13:45 - ',
 '23/09/25, 13:45 - ',
 '23/09/25, 13:46 - ',
 '23/09/25, 13:46 - ',
 '23/09/25, 13:47 - ',
 '23/09/25, 13:53 - ',
 '23/09/25, 14:03 - ',
 '23/09/25, 14:03 - ',
 '23/09/25, 14:03 - ',
 '23/09/25, 14:03 - ',
 '23/09/25, 14:04 - ',
 '23/09/25, 14:10 - ',
 '23/09/25, 14:11 - ',
 '23/09/25, 14:12 - ',
 '23/09/25, 14:12 - ',
 '23/09/25, 14:12 - ',
 '23/09/25, 14:13 - ',
 '23/09/25, 14:13 - ',
 '23/09/25, 14:20 - ',
 '23/09/25, 15:00 - ',
 '23/09/25, 15:00 - ',
 '23/09/25, 15:01 - ',
 '23/09/25, 15:02 - ',
 '23/09/25, 15:02 - ',
 '23/09/25, 15:04 - ',
 '23/09/25, 17:28 - ',
 '23/09/25, 17:30 - ',
 '23/09/25, 17:35 - ',
 '23/09/25, 17:35 - ',
 '23/09/25, 17:35 - ',
 '23/09/25, 17:36 - ',
 '23/09/25, 18:39 - ',
 '23/09/25, 18:45 - ',
 '23/09/25, 18:45 - ',
 '24/09/25, 10:45 - ',
 '24/09/25, 10:55 - ',
 '24/09/25, 12:01 - ',
 '24/09/25, 12:15 - ',
 '24/09/25, 12:16 - ',
 '24/09/25, 12:17 - ',
 '25/09/25, 10:33 - ',
 '25/09/25, 12:40 - ',
 '25/09/25, 13:41 - ',
 '25/09/25, 13:46 - ',
 '25/09/25, 15:26 - ',
 '25/09/25, 15:30 - ',
 '25/09/25, 15:34 - ',
 '25/09/25, 15:34 - ',
 '25/09/25, 18:24 - ',
 '25/09/25, 18:26 - ',
 '25/09/25, 18:27 - ',
 '25/09/25, 18:27 - ',
 '25/09/25, 18:27 - ',
 '25/09/25, 22:00 - ',
 '25/09/25, 22:29 - ',
 '25/09/25, 22:29 - ',
 '25/09/25, 22:29 - ',
 '25/09/25, 22:29 - ',
 '26/09/25, 00:19 - ',
 '26/09/25, 00:19 - ',
 '26/09/25, 00:24 - ',
 '26/09/25, 08:21 - ',
 '26/09/25, 08:30 - ',
 '26/09/25, 08:32 - ',
 '26/09/25, 08:32 - ',
 '26/09/25, 09:02 - ',
 '28/09/25, 10:57 - ',
 '28/09/25, 22:40 - ',
 '28/09/25, 22:41 - ',
 '28/09/25, 22:41 - ',
 '29/09/25, 00:17 - ',
 '29/09/25, 13:54 - ',
 '29/09/25, 13:55 - ',
 '29/09/25, 15:28 - ',
 '29/09/25, 19:45 - ',
 '29/09/25, 20:14 - ',
 '29/09/25, 20:17 - ',
 '29/09/25, 20:17 - ',
 '29/09/25, 20:18 - ',
 '29/09/25, 20:18 - ',
 '29/09/25, 20:19 - ',
 '29/09/25, 20:19 - ',
 '29/09/25, 20:20 - ',
 '29/09/25, 20:21 - ',
 '29/09/25, 21:20 - ',
 '30/09/25, 15:27 - ',
 '30/09/25, 16:06 - ',
 '30/09/25, 16:06 - ',
 '30/09/25, 19:59 - ',
 '01/10/25, 11:17 - ',
 '01/10/25, 11:18 - ',
 '01/10/25, 21:04 - ',
 '01/10/25, 22:53 - ',
 '02/10/25, 17:52 - ',
 '02/10/25, 21:05 - ',
 '03/10/25, 22:34 - ',
 '03/10/25, 22:35 - ',
 '03/10/25, 22:35 - ',
 '03/10/25, 22:35 - ',
 '03/10/25, 22:36 - ',
 '03/10/25, 22:36 - ',
 '03/10/25, 22:36 - ',
 '03/10/25, 22:37 - ',
 '03/10/25, 22:37 - ',
 '04/10/25, 13:50 - ',
 '04/10/25, 14:41 - ',
 '04/10/25, 14:53 - ',
 '04/10/25, 15:02 - ',
 '04/10/25, 15:02 - ',
 '04/10/25, 15:04 - ',
 '04/10/25, 15:04 - ',
 '04/10/25, 15:05 - ',
 '04/10/25, 15:05 - ',
 '04/10/25, 15:05 - ',
 '04/10/25, 20:51 - ',
 '04/10/25, 20:58 - ',
 '04/10/25, 21:00 - ',
 '04/10/25, 21:00 - ',
 '04/10/25, 21:01 - ',
 '04/10/25, 21:01 - ',
 '04/10/25, 21:01 - ',
 '04/10/25, 21:01 - ',
 '04/10/25, 21:01 - ',
 '04/10/25, 21:01 - ',
 '04/10/25, 21:02 - ',
 '04/10/25, 21:02 - ',
 '04/10/25, 21:02 - ',
 '04/10/25, 21:02 - ',
 '04/10/25, 21:02 - ',
 '04/10/25, 21:02 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:03 - ',
 '04/10/25, 21:04 - ',
 '04/10/25, 21:04 - ',
 '04/10/25, 21:05 - ',
 '04/10/25, 21:05 - ',
 '04/10/25, 21:05 - ',
 '04/10/25, 21:06 - ',
 '04/10/25, 21:06 - ',
 '04/10/25, 21:06 - ',
 '04/10/25, 21:06 - ',
 '04/10/25, 21:07 - ',
 '04/10/25, 21:07 - ',
 '04/10/25, 21:07 - ',
 '04/10/25, 21:07 - ',
 '04/10/25, 21:07 - ',
 '04/10/25, 21:08 - ',
 '04/10/25, 21:08 - ',
 '04/10/25, 21:08 - ',
 '04/10/25, 21:08 - ',
 '04/10/25, 21:08 - ',
 '04/10/25, 21:08 - ',
 '04/10/25, 21:08 - ',
 '04/10/25, 21:09 - ',
 '04/10/25, 21:09 - ',
 '04/10/25, 21:09 - ',
 '04/10/25, 21:09 - ',
 '04/10/25, 21:09 - ',
 '04/10/25, 21:09 - ',
 '04/10/25, 21:09 - ',
 '04/10/25, 21:09 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:10 - ',
 '04/10/25, 21:11 - ',
 '04/10/25, 21:11 - ',
 '04/10/25, 21:11 - ',
 '04/10/25, 21:11 - ',
 '04/10/25, 21:11 - ',
 '04/10/25, 21:11 - ',
 '04/10/25, 21:11 - ',
 '04/10/25, 21:11 - ',
 '04/10/25, 21:11 - ',
 '04/10/25, 21:11 - ',
 '04/10/25, 21:12 - ',
 '04/10/25, 21:12 - ',
 '04/10/25, 21:12 - ',
 '04/10/25, 21:12 - ',
 '04/10/25, 21:12 - ',
 '04/10/25, 21:12 - ',
 '04/10/25, 21:13 - ',
 '04/10/25, 21:13 - ',
 '04/10/25, 21:13 - ',
 '04/10/25, 21:13 - ',
 '04/10/25, 21:13 - ',
 '04/10/25, 21:13 - ',
 '04/10/25, 21:13 - ',
 '04/10/25, 21:13 - ',
 '04/10/25, 21:14 - ',
 '04/10/25, 21:14 - ',
 '04/10/25, 21:14 - ',
 '04/10/25, 21:14 - ',
 '04/10/25, 21:14 - ',
 '04/10/25, 21:15 - ',
 '04/10/25, 21:15 - ',
 '04/10/25, 21:15 - ',
 '04/10/25, 21:15 - ',
 '04/10/25, 21:15 - ',
 '04/10/25, 21:15 - ',
 '04/10/25, 21:15 - ',
 '04/10/25, 21:16 - ',
 '04/10/25, 21:16 - ',
 '04/10/25, 21:16 - ',
 '04/10/25, 21:16 - ',
 '04/10/25, 21:16 - ',
 '04/10/25, 21:16 - ',
 '04/10/25, 21:16 - ',
 '04/10/25, 21:16 - ',
 '04/10/25, 21:16 - ',
 '04/10/25, 21:17 - ',
 '04/10/25, 21:17 - ',
 '04/10/25, 21:17 - ',
 '04/10/25, 21:17 - ',
 '04/10/25, 21:17 - ',
 '04/10/25, 21:17 - ',
 '04/10/25, 21:17 - ',
 '04/10/25, 21:18 - ',
 '04/10/25, 21:18 - ',
 '04/10/25, 21:18 - ',
 '04/10/25, 21:18 - ',
 '04/10/25, 21:18 - ',
 '04/10/25, 21:18 - ',
 '04/10/25, 21:18 - ',
 '04/10/25, 21:18 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:19 - ',
 '04/10/25, 21:20 - ',
 '04/10/25, 21:20 - ',
 '04/10/25, 21:20 - ',
 '04/10/25, 21:20 - ',
 '04/10/25, 21:20 - ',
 '04/10/25, 21:21 - ',
 '04/10/25, 21:21 - ',
 '04/10/25, 21:22 - ',
 '04/10/25, 21:22 - ',
 '04/10/25, 21:22 - ',
 '04/10/25, 21:22 - ',
 '04/10/25, 21:23 - ',
 '04/10/25, 21:23 - ',
 '04/10/25, 21:23 - ',
 '04/10/25, 21:24 - ',
 '04/10/25, 21:24 - ',
 '04/10/25, 21:25 - ',
 '04/10/25, 21:29 - ',
 '04/10/25, 21:29 - ',
 '04/10/25, 21:30 - ',
 '04/10/25, 21:31 - ',
 '04/10/25, 21:56 - ',
 '05/10/25, 00:40 - ',
 '05/10/25, 10:18 - ',
 '05/10/25, 10:19 - ',
 '05/10/25, 10:22 - ',
 '05/10/25, 10:23 - ',
 '05/10/25, 10:23 - ',
 '05/10/25, 10:23 - ',
 '05/10/25, 10:24 - ',
 '05/10/25, 10:24 - ',
 '05/10/25, 10:24 - ',
 '05/10/25, 10:24 - ',
 '05/10/25, 10:26 - ',
 '05/10/25, 10:30 - ',
 '05/10/25, 10:31 - ',
 '05/10/25, 10:31 - ',
 '05/10/25, 10:31 - ',
 '05/10/25, 10:31 - ',
 '05/10/25, 10:31 - ',
 '05/10/25, 10:36 - ',
 '05/10/25, 10:38 - ',
 '05/10/25, 10:58 - ',
 '05/10/25, 10:59 - ',
 '05/10/25, 14:54 - ',
 '05/10/25, 16:29 - ',
 '05/10/25, 16:29 - ',
 '05/10/25, 16:29 - ',
 '05/10/25, 16:29 - ',
 '05/10/25, 16:29 - ',
 '06/10/25, 21:16 - ',
 '06/10/25, 21:16 - ',
 '06/10/25, 21:16 - ',
 '06/10/25, 21:17 - ',
 '06/10/25, 21:17 - ',
 '06/10/25, 21:17 - ',
 '06/10/25, 21:17 - ',
 '06/10/25, 21:18 - ',
 '06/10/25, 21:20 - ',
 '06/10/25, 22:13 - ',
 '06/10/25, 22:13 - ',
 '06/10/25, 22:13 - ',
 '06/10/25, 22:13 - ',
 '06/10/25, 22:14 - ',
 '06/10/25, 22:14 - ',
 '07/10/25, 21:23 - ',
 '07/10/25, 21:24 - ',
 '07/10/25, 21:26 - ',
 '07/10/25, 21:27 - ',
 '08/10/25, 10:40 - ',
 '08/10/25, 14:54 - ',
 '08/10/25, 22:07 - ',
 '08/10/25, 22:08 - ',
 '08/10/25, 22:23 - ',
 '08/10/25, 22:24 - ',
 '09/10/25, 12:11 - ',
 '09/10/25, 12:46 - ',
 '09/10/25, 14:46 - ',
 '10/10/25, 01:45 - ',
 '10/10/25, 01:45 - ',
 '10/10/25, 02:21 - ',
 '10/10/25, 02:22 - ',
 '10/10/25, 02:22 - ',
 '10/10/25, 10:47 - ',
 '10/10/25, 10:48 - ',
 '10/10/25, 13:03 - ',
 '10/10/25, 13:03 - ',
 '10/10/25, 13:04 - ',
 '10/10/25, 13:04 - ',
 '10/10/25, 13:10 - ',
 '10/10/25, 13:12 - ',
 '10/10/25, 13:12 - ',
 '10/10/25, 13:13 - ',
 '10/10/25, 13:14 - ',
 '10/10/25, 13:14 - ',
 '10/10/25, 13:14 - ',
 '10/10/25, 13:14 - ',
 '10/10/25, 13:14 - ',
 '10/10/25, 13:14 - ',
 '10/10/25, 13:18 - ',
 '10/10/25, 13:20 - ',
 '10/10/25, 14:58 - ',
 '10/10/25, 18:44 - ',
 '10/10/25, 18:47 - ',
 '10/10/25, 18:54 - ',
 '10/10/25, 22:18 - ',
 '13/10/25, 16:37 - ',
 '13/10/25, 16:38 - ',
 '14/10/25, 11:13 - ',
 '14/10/25, 11:13 - ',
 '15/10/25, 00:17 - ',
 '15/10/25, 00:17 - ',
 '15/10/25, 10:21 - ',
 '15/10/25, 14:48 - ',
 '15/10/25, 14:48 - ',
 '15/10/25, 14:59 - ',
 '15/10/25, 14:59 - ',
 '15/10/25, 14:59 - ',
 '15/10/25, 14:59 - ',
 '15/10/25, 15:06 - ',
 '15/10/25, 15:06 - ',
 '15/10/25, 15:42 - ',
 '15/10/25, 15:47 - ',
 '15/10/25, 15:47 - ',
 '15/10/25, 15:47 - ',
 '15/10/25, 15:56 - ',
 '15/10/25, 15:56 - ',
 '15/10/25, 15:57 - ',
 '15/10/25, 15:57 - ',
 '15/10/25, 15:59 - ',
 '15/10/25, 16:10 - ',
 '15/10/25, 17:33 - ',
 '15/10/25, 17:34 - ',
 '15/10/25, 17:34 - ',
 '16/10/25, 09:01 - ',
 '16/10/25, 09:14 - ',
 '16/10/25, 13:51 - ',
 '16/10/25, 19:11 - ',
 '16/10/25, 19:12 - ',
 '16/10/25, 19:19 - ',
 '16/10/25, 19:19 - ',
 '17/10/25, 10:59 - ',
 '17/10/25, 10:59 - ',
 '17/10/25, 10:59 - ',
 '17/10/25, 10:59 - ',
 '17/10/25, 11:00 - ',
 '17/10/25, 11:00 - ',
 '17/10/25, 11:00 - ',
 '17/10/25, 19:22 - ',
 '17/10/25, 19:22 - ',
 '17/10/25, 19:24 - ',
 '17/10/25, 20:18 - ',
 '17/10/25, 20:18 - ',
 '17/10/25, 21:03 - ',
 '17/10/25, 21:05 - ',
 '18/10/25, 17:26 - ',
 '18/10/25, 20:32 - ',
 '19/10/25, 23:30 - ',
 '19/10/25, 23:40 - ',
 '19/10/25, 23:56 - ',
 '20/10/25, 00:26 - ',
 '20/10/25, 00:26 - ',
 '20/10/25, 00:55 - ',
 '20/10/25, 01:45 - ',
 '20/10/25, 09:54 - ',
 '20/10/25, 10:32 - ',
 '21/10/25, 15:40 - ',
 '21/10/25, 15:41 - ',
 '21/10/25, 15:41 - ',
 '21/10/25, 15:53 - ',
 '21/10/25, 15:54 - ',
 '21/10/25, 17:35 - ',
 '21/10/25, 19:37 - ',
 '21/10/25, 19:37 - ',
 '21/10/25, 19:38 - ',
 '21/10/25, 19:46 - ',
 '21/10/25, 19:52 - ',
 '21/10/25, 19:57 - ',
 '21/10/25, 19:57 - ',
 '21/10/25, 20:20 - ',
 '21/10/25, 20:20 - ',
 '22/10/25, 21:22 - ',
 '22/10/25, 21:22 - ',
 '23/10/25, 11:25 - ',
 '23/10/25, 11:26 - ',
 '23/10/25, 11:27 - ',
 '23/10/25, 11:27 - ',
 '23/10/25, 11:27 - ',
 '23/10/25, 11:27 - ',
 '23/10/25, 11:28 - ',
 '23/10/25, 11:29 - ',
 '23/10/25, 11:46 - ',
 '23/10/25, 20:11 - ',
 '23/10/25, 20:12 - ',
 '23/10/25, 20:17 - ',
 '23/10/25, 20:18 - ',
 '23/10/25, 20:20 - ',
 '23/10/25, 20:20 - ',
 '23/10/25, 20:21 - ',
 '23/10/25, 20:46 - ',
 '23/10/25, 20:46 - ',
 '23/10/25, 22:29 - ',
 '23/10/25, 22:29 - ',
 '23/10/25, 22:29 - ',
 '23/10/25, 22:31 - ',
 '23/10/25, 22:31 - ',
 '23/10/25, 22:31 - ',
 '23/10/25, 22:31 - ',
 '23/10/25, 22:31 - ',
 '23/10/25, 22:32 - ',
 '25/10/25, 04:51 - ',
 '25/10/25, 06:55 - ',
 '25/10/25, 07:01 - ',
 '25/10/25, 07:01 - ',
 '25/10/25, 07:01 - ',
 '25/10/25, 07:01 - ',
 '25/10/25, 07:02 - ',
 '25/10/25, 07:02 - ',
 '25/10/25, 07:03 - ',
 '25/10/25, 07:03 - ',
 '25/10/25, 07:03 - ',
 '25/10/25, 07:04 - ',
 '25/10/25, 07:04 - ',
 '25/10/25, 07:05 - ',
 '25/10/25, 07:36 - ',
 '25/10/25, 07:40 - ',
 '25/10/25, 07:42 - ',
 '25/10/25, 07:44 - ',
 '25/10/25, 08:01 - ',
 '25/10/25, 08:02 - ',
 '25/10/25, 08:02 - ',
 '25/10/25, 08:02 - ',
 '25/10/25, 08:02 - ',
 '25/10/25, 08:25 - ',
 '25/10/25, 08:26 - ',
 '25/10/25, 08:37 - ',
 '25/10/25, 09:05 - ',
 '25/10/25, 10:49 - ',
 '25/10/25, 10:59 - ',
 '25/10/25, 11:45 - ',
 '25/10/25, 11:47 - ',
 '25/10/25, 11:47 - ',
 '25/10/25, 11:47 - ',
 '25/10/25, 12:18 - ',
 '26/10/25, 09:39 - ',
 '27/10/25, 16:21 - ',
 '27/10/25, 16:22 - ',
 '27/10/25, 16:22 - ',
 '27/10/25, 16:23 - ',
 '27/10/25, 17:08 - ',
 '27/10/25, 17:08 - ',
 '27/10/25, 19:41 - ',
 '27/10/25, 19:42 - ',
 '28/10/25, 10:11 - ',
 '29/10/25, 11:10 - ',
 '29/10/25, 17:42 - ',
 '29/10/25, 17:42 - ',
 '29/10/25, 17:54 - ',
 '29/10/25, 17:55 - ',
 '29/10/25, 23:45 - ',
 '30/10/25, 11:49 - ',
 '31/10/25, 18:11 - ',
 '02/11/25, 10:05 - ',
 '04/11/25, 10:35 - ',
 '04/11/25, 15:01 - ',
 '04/11/25, 23:07 - ',
 '04/11/25, 23:13 - ',
 '06/11/25, 11:15 - ',
 '08/11/25, 13:43 - ',
 '10/11/25, 18:57 - ',
 '10/11/25, 18:59 - ',
 '10/11/25, 19:00 - ',
 '10/11/25, 19:01 - ',
 '10/11/25, 19:01 - ',
 '10/11/25, 19:05 - ',
 '10/11/25, 19:07 - ',
 '10/11/25, 19:07 - ',
 '10/11/25, 19:07 - ',
 '10/11/25, 20:11 - ',
 '10/11/25, 20:12 - ',
 '10/11/25, 20:22 - ',
 '10/11/25, 20:22 - ',
 '10/11/25, 20:27 - ',
 '10/11/25, 20:29 - ',
 '10/11/25, 20:29 - ',
 '10/11/25, 20:29 - ',
 '10/11/25, 20:30 - ',
 '10/11/25, 20:30 - ',
 '10/11/25, 23:15 - ',
 '11/11/25, 06:29 - ',
 '11/11/25, 09:44 - ',
 '11/11/25, 16:58 - ',
 '11/11/25, 20:09 - ',
 '12/11/25, 11:12 - ',
 '12/11/25, 16:06 - ',
 '12/11/25, 20:29 - ',
 '13/11/25, 11:12 - ',
 '13/11/25, 11:30 - ',
 '13/11/25, 14:10 - ',
 '14/11/25, 09:43 - ',
 '14/11/25, 11:15 - ',
 '14/11/25, 11:16 - ',
 '14/11/25, 15:47 - ',
 '14/11/25, 15:47 - ',
 '14/11/25, 15:48 - ',
 '14/11/25, 15:49 - ',
 '14/11/25, 15:49 - ',
 '14/11/25, 15:50 - ',
 '14/11/25, 15:51 - ',
 '14/11/25, 15:53 - ',
 '14/11/25, 15:55 - ',
 '14/11/25, 15:55 - ',
 '14/11/25, 15:58 - ',
 '14/11/25, 15:59 - ',
 '14/11/25, 16:04 - ',
 '14/11/25, 16:04 - ',
 '14/11/25, 19:09 - ',
 '14/11/25, 21:19 - ',
 '15/11/25, 00:31 - ',
 '15/11/25, 00:36 - ',
 '15/11/25, 00:36 - ',
 '15/11/25, 00:37 - ',
 '15/11/25, 00:38 - ',
 '15/11/25, 00:39 - ',
 '15/11/25, 00:39 - ',
 '15/11/25, 00:41 - ',
 '15/11/25, 00:42 - ',
 '15/11/25, 07:24 - ',
 '15/11/25, 12:49 - ',
 '17/11/25, 00:09 - ',
 '17/11/25, 00:14 - ',
 '17/11/25, 00:16 - ',
 '17/11/25, 00:17 - ',
 '17/11/25, 08:20 - ',
 '17/11/25, 08:30 - ',
 '17/11/25, 08:31 - ',
 '17/11/25, 09:01 - ',
 '17/11/25, 09:01 - ',
 '17/11/25, 09:24 - ',
 '17/11/25, 11:03 - ',
 '17/11/25, 11:04 - ',
 '17/11/25, 16:18 - ',
 '17/11/25, 16:18 - ',
 '17/11/25, 16:44 - ',
 '17/11/25, 21:51 - ',
 '17/11/25, 22:59 - ',
 '17/11/25, 23:01 - ',
 '18/11/25, 14:08 - ',
 '18/11/25, 14:16 - ',
 '18/11/25, 15:12 - ',
 '18/11/25, 17:55 - ',
 '18/11/25, 17:55 - ',
 '18/11/25, 17:55 - ',
 '18/11/25, 17:56 - ',
 '18/11/25, 17:56 - ',
 '18/11/25, 17:56 - ',
 '18/11/25, 17:56 - ',
 '18/11/25, 17:56 - ',
 '18/11/25, 17:56 - ',
 '19/11/25, 10:38 - ',
 '19/11/25, 10:38 - ',
 '19/11/25, 10:55 - ',
 '19/11/25, 10:55 - ',
 '19/11/25, 11:00 - ',
 '19/11/25, 11:01 - ',
 '19/11/25, 11:02 - ',
 '19/11/25, 11:03 - ',
 '19/11/25, 16:18 - ',
 '20/11/25, 15:32 - ',
 '20/11/25, 15:45 - ',
 '21/11/25, 10:18 - ',
 '21/11/25, 13:06 - ',
 '24/11/25, 13:09 - ',
 '24/11/25, 13:10 - ',
 '24/11/25, 13:10 - ',
 '24/11/25, 13:22 - ',
 '24/11/25, 13:22 - ',
 '24/11/25, 13:22 - ',
 '24/11/25, 13:34 - ',
 '24/11/25, 13:54 - ',
 '24/11/25, 13:59 - ',
 '24/11/25, 13:59 - ',
 '24/11/25, 14:03 - ',
 '24/11/25, 14:03 - ',
 '24/11/25, 16:13 - ',
 '24/11/25, 16:14 - ',
 '24/11/25, 16:15 - ',
 '24/11/25, 16:15 - ',
 '24/11/25, 20:52 - ',
 '24/11/25, 20:52 - ',
 '24/11/25, 21:12 - ',
 '24/11/25, 21:19 - ',
 '24/11/25, 21:22 - ',
 '24/11/25, 21:32 - ',
 '24/11/25, 21:37 - ',
 '24/11/25, 21:37 - ',
 '24/11/25, 21:38 - ',
 '24/11/25, 21:39 - ',
 '24/11/25, 21:39 - ',
 '24/11/25, 21:51 - ',
 '24/11/25, 21:51 - ',
 '24/11/25, 21:51 - ',
 '24/11/25, 22:03 - ',
 '25/11/25, 10:10 - ',
 '25/11/25, 10:10 - ',
 '25/11/25, 10:13 - ',
 '25/11/25, 10:20 - ',
 '25/11/25, 11:00 - ',
 '25/11/25, 13:02 - ',
 '25/11/25, 13:02 - ',
 '25/11/25, 18:29 - ',
 '25/11/25, 20:06 - ',
 '25/11/25, 20:06 - ',
 '25/11/25, 20:09 - ',

In [ ]:
df = pd.DataFrame({'user_message': messages, 'message_date': dates})

df['message_date'] = pd.to_datetime(df['message_date'], format='%d/%m/%y, %H:%M - ')

df.rename(columns={'message_date': 'date'}, inplace= True)

df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. O... 2025-09-12 16:04:00
1  Aditya AA EC GLA: Communication k assignment h... 2025-09-12 20:34:00
2                        Vinayak GLA 2nd Year: Yes\n 2025-09-12 20:40:00
3                        +91 788 725 2559: Bhej do\n 2025-09-12 20:53:00
4                            +91 84398 26596: Bhjo\n 2025-09-12 20:53:00

In [15]:
df.shape

(2275, 2)

In [20]:
users = []
messages = []

for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s', message)

    if entry[1:]:
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['users'] = users
df['messages'] = messages
df.drop(columns=['user_message'], inplace=True)

df.head()

,date,users,messages
0,2025-09-12 16:04:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2025-09-12 20:34:00,Aditya AA EC GLA,Communication k assignment hogyaa kisika...?\n
2,2025-09-12 20:40:00,Vinayak GLA 2nd Year,Yes\n
3,2025-09-12 20:53:00,+91 788 725 2559,Bhej do\n
4,2025-09-12 20:53:00,+91 84398 26596,Bhjo\n